name: CI (disabled)

on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "CI disabled here to avoid flaky nix fmt. Use repository nixos-config for formatter checks."
