name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  fmt:
    name: nix fmt (check only)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Nix formatter check (no lockfile writes)
        run: |
          set -euo pipefail
          # Prevent flake.lock updates and run formatter in check mode
          nix fmt --no-write-lock-file -- --check || {
            echo "::error ::Formatting issues found. Please run 'nix fmt' locally and commit changes.";
            exit 1;
          }
