name: Link Check
on:
  push:
  pull_request:
  schedule:
    - cron: '0 3 * * 1'
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v2
        with:
          args: --no-progress --verbose --exclude-mail --max-redirects 5 --retry-wait-time 2 --timeout 30s .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

