name: Nix format (disabled)

on:
  workflow_dispatch:

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Nix format CI is disabled in this repo. Run 'nix fmt' locally if desired."
